name: Atlas
on:
  # Run whenever code is changed in the master branch,
  # change this to your root branch.
  push:
    branches:
      - main
  # Run on PRs where something changed under the `path/to/migration/dir/` directory.
  pull_request:
jobs:
  lint:
    services:
      # Spin up a mysql:8.0.29 container to be used as the dev-database for analysis.
      mysql:
        image: mcr.microsoft.com/mssql/server
        env:
          MSSQL_SA_PASSWORD: myStrongPassword!
          ACCEPT_EULA: Y
        ports:
          - "1433:1433"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.1
        with:
          fetch-depth: 0 # Mandatory unless "latest" is set below.
      - uses: ariga/atlas-action@v0
        env:
          ATLAS_TOKEN: ${{ secrets.ATLAS_TOKEN }}
        with:
          dir: 'migrations'
          dev-url: mssql://sa:myStrongPassword!@localhost:1433/dev
          cloud-token: ${{ secrets.ATLAS_TOKEN }}

          
  #sync:
  #  needs: lint
  #  if: github.ref == 'refs/heads/main'
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@v3
  #    - uses: ariga/atlas-sync-action@v0
  #      with:
  #        dir: 'migrations'
  #        driver: mysql # or: postgres | sqlite
  #        cloud-token: ${{ secrets.ARIGA_TOKEN }}
