name: Integration Test (Postgres)
on:
  push:
jobs:
  integration:
    services:
      postgres10:
        image: postgres:10
        env:
          POSTGRES_DB: test
          POSTGRES_PASSWORD: pass
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.1
      - name: Install Atlas
        run: |
          curl -sSf https://atlasgo.sh | sh
      - run: |
          atlas migrate apply --dir migrations/ -u postgres://postgres:pass@localhost:5432/test
      - run: |
          echo "Run your tests here!"
